version: "3.8"

services:
  boms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boms-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
    volumes:
      - boms_uploads_data:/app/public/uploads
    networks:
      - boms_default

networks:
  boms_default:
    driver: bridge

volumes:
  boms_uploads_data:
    driver: local
